name: Terraform Deploy

on:
  push:
    branches:
      - main
      - release/*

permissions:
  id-token: write
  contents: read

jobs:
  my_job:
    name: deploy runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: c92e9a32-07ec-4655-98f1-56352692d424
          tenant-id: a2209f67-16ac-4447-8b9a-8d98c9c06b18
          subscription-id: 3d1ce785-6c4d-4565-bb5e-3b46939260a6
          auth-type: SERVICE_PRINCIPAL

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: parent_module/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: parent_module/dev

      - name: Terraform Fmt
        run: terraform fmt 
        working-directory: parent_module/dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: parent_module/dev
